STIKERS = [
    'CAACAgIAAxkBAAEBFIFfFy53DFJBAt0eGSwZEMzv8fQkfwAC6QcAAvoLtgiG3er2ahNmXxoE',
    'CAACAgIAAxkBAAEBFH1fFy4kIQABI73GGIz9fnx3AU7V1BAAAgsAA2v--RKeNMHpSoi6LRoE',
    'CAACAgIAAxkBAAEBNcNfOVbjRewriKHkhVmSr8t7sU-xVAACBwADFgqsEA7M9oZNeed8GgQ',
    'CAACAgIAAxkBAAEBNd5fOYpJcy1g5X9jBPcSTJ3prlc2MAACWgADq8pZIb4PS42uN-U_GgQ',
    'CAACAgIAAxkBAAEBNe5fOYrgly-koyAmA-2Y_032gc4uJAACMgADq8pZIf-utREdSfLYGgQ',
    'CAACAgIAAxkBAAEBNfhfOYu2O_47vRA7Q7NjiPvgpC_AFQACQQADq8pZIR5qydh5tpkbGgQ',
]


cant_hear_you = [
    'CAACAgIAAxkBAAEBNf5fOYvSU3-z12_NdfsdyWNXLg1megACNgADq8pZIRE8LKnNnjwnGgQ',
    'CAACAgIAAxkBAAEBNfBfOYrw2ovs8wh0QqgHlLs-VkICDwACNQADq8pZIepTmAUSKLd2GgQ',
]