version: '3.8'

services:
  db:
    container_name: database
    image: postgres:latest
    env_file:
      - '.env'
    environment:
      DATABASE_NAME: $DATABASE_NAME
      PG_PASSWORD: $PGPASSWORD
      PG_USER: $PGUSER
      POSTGRES_HOST_AUTH_METHOD: "trust"
    restart: always
    ports:
      - "5432:5432"
    networks:
      - my_network
    volumes:
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
      - ./pgdata:/var/lib/postgresql/data

  django:
    container_name: django_app
    build: ./web
    command:
      bash -c "python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000 --noreload"
    ports:
      - 8000:8000
    networks:
      - my_network
    restart:
      always
    env_file:
      - '.env'
    volumes:
    - .:/urs/src/web
    depends_on:
      - db

  tgbot:
    container_name: tg_bot
    build:
      context: ./tg-bot
    command:
      python app.py
    networks:
      - my_network
    volumes:
      - .:/src
    restart:
      always
    env_file:
      - '.env'
    depends_on:
      - db
      - django

volumes:
  pgdata:

networks:
  my_network:
    driver: bridge

