version: '3.8'

services:
  db:
    container_name:
      database
    image:
      postgres:latest
    env_file:
      - '.env'
    environment:
      PG_PASSWORD:
        $PGPASSWORD
      POSTGRES_HOST_AUTH_METHOD:
        "trust"
    restart:
      always
    ports:
      - "5432:5432"  # поменять на сервере
    networks:
     - my_network
    volumes:
      - ./postgres:/var/lib/postgresql

  django:
    container_name:
      django_app
    build:
      context: .
    command:
      python django_app.py runserver 0.0.0.0:8000 --noreload
    ports:
      - 8000:8000
    networks:
      - my_network
    restart:
      always
    env_file:
      - '.env'
    depends_on:
      - db

  tgbot:
    container_name:
      alleycat-bot
    build:
      context: .
    command:
      python app.py
    networks:
      - my_network
    volumes:
      - .:/src
    restart:
      always
    env_file:
      - '.env'
    depends_on:
      - db
      - django

networks:
  my_network:
    driver: bridge

