# Generated by Django 3.1.7 on 2021-03-11 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckPoints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_point', models.CharField(max_length=255, null=True, verbose_name='Название чекпоинта')),
                ('latitude', models.FloatField(null=True, verbose_name='Широта-Х')),
                ('longitude', models.FloatField(null=True, verbose_name='Долгота-Y')),
            ],
            options={
                'verbose_name': 'Чек поинт',
                'verbose_name_plural': 'Чек поинты',
            },
        ),
        migrations.CreateModel(
            name='RacingDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_start', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время старта гонки')),
            ],
            options={
                'verbose_name': 'Время и дата начала гонки',
                'verbose_name_plural': 'Время старта гонки',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('telegram_id', models.BigIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='ID телеграм')),
                ('fullname', models.CharField(max_length=100, null=True, verbose_name='Имя пользователя')),
                ('username', models.CharField(max_length=100, null=True, verbose_name='Username в телеграм')),
                ('gender', models.CharField(max_length=100, verbose_name='Пол')),
                ('bicycle', models.CharField(max_length=100, verbose_name='Тип велосипеда')),
            ],
            options={
                'verbose_name': 'Участник',
                'verbose_name_plural': 'Участники',
            },
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finish_time', models.DateTimeField(auto_now=True, verbose_name='Время финиша')),
                ('total_time', models.DurationField(verbose_name='Время гонки')),
                ('fullname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.users', verbose_name='Имя пользователя')),
                ('start_time', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration.racingdate', verbose_name='Время старта')),
            ],
            options={
                'verbose_name': 'Время участника и фото',
                'verbose_name_plural': 'Время участников и фото',
            },
        ),
    ]
